### ISSUE TITLE
Verica modifica label

### ISSUE THREAD

**Issue by apiccinini** [anticorruzione/italia-conf#3]
provo a mettere io una label

**Comment by apiccinini** [comment]
non posso modificare la label

**Comment by apiccinini** [comment]
fghfh

**Comment by anac-uscp** [comment]
<p>commento 3 ultimo</p>

**Comment by stalex1** [comment]
test 2

**Comment by stalex1** [comment]
test 5

**Comment by anac-uscp** [comment]
<p>altro ultimo commento</p>

**Comment by anac-uscp** [comment]
<p>RISOLTO!!!</p>

**Comment by anac-uscp** [comment]
<p>RISOLTO!!!</p>

**Comment by anac-uscp** [comment]
<p>chiusura ticket</p>

**Comment by anac-uscp** [comment]
<p>test di chiusura commento</p>

**Comment by anac-uscp** [comment]
<p>Chisura issu test docker</p>

**Comment by anac-uscp** [comment]
<p>test chiusura 2</p>

**Comment by anac-uscp** [comment]
<p>sadasdasdasdasdasdasdasd</p>

**Comment by anac-uscp** [comment]
<p>3 commento</p>

**Comment by anac-uscp** [comment]
<p>commento per fvoe</p>

**Comment by anac-uscp** [comment]
<p>chiusura ticket</p>

**Comment by anac-uscp** [comment]
<p>chiusura ticket</p>
